version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
  web:
    build: app
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: ./start.sh
    restart: always

  gateway:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-80}:80"
      - "${SSL_PORT:-443}:443"
    volumes:
      - './volumes/logs:/var/log/nginx'
      - './gateway/nginx/conf:/etc/nginx/conf.d'
      - './gateway/nginx/ssl:/etc/ssl'
    depends_on:
      - web
