version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
  web:
    build: app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ./start.sh
    restart: always
