# Generated by Django 2.2.1 on 2019-05-30 14:49

from django.db import migrations


def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Guests')
    Group.objects.get_or_create(name='PropertyStaff')


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('auth', '0011_update_proxy_permissions')
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]
