# Generated by Django 2.2.1 on 2019-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20190530_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Lisbon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default='Rua da Liberdade', max_length=100),
            preserve_default=False,
        ),
    ]
