# Generated by Django 2.2.1 on 2019-05-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20190530_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Property')),
            ],
        ),
    ]
